/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import struts.form.LoginForm;
import java.sql.*;

/** 
 * MyEclipse Struts
 * Creation date: 11-28-2011
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/login.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/login.jsp"
 * @struts.action-forward name="success" path="/welcome.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;
		String className="com.mysql.jdbc.Driver";
		String url="jdbc:mysql://localhost:3306/strus";
		int i=0;
		try {
			Class.forName(className);
			Connection con = DriverManager.getConnection(url,"root","12345");
			String sql="select * from user where username='"+loginForm.getUsername()+"'and password='"+loginForm.getPassword()+"'";
			PreparedStatement prm=con.prepareStatement(sql);
			ResultSet rs=prm.executeQuery();
			if(rs.next()){
	    		i=1;
	    	}
	    	else{
	    		i=3;
	    	}
			
			
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(i==1){
		 String username=loginForm.getUsername();
		 HttpSession session = request.getSession(); 
		 session.setAttribute("username", username);  
		 return mapping.findForward("success");	
		}
		else{
			return mapping.findForward("fail");
		}
		
	}
}