/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import struts.form.RegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 11-28-2011
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="registerForm" input="/register.jsp" scope="request" validate="true"
 * @struts.action-forward name="fail" path="/register.jsp"
 * @struts.action-forward name="success" path="/welcome.jsp"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated method stub
		String className="com.mysql.jdbc.Driver";
		String url="jdbc:mysql://localhost:3306/strus";
		int i=0;
		try {
			Class.forName(className);
			Connection con = DriverManager.getConnection(url,"root","12345");
			String sql="insert into user (username,password) values ('"+registerForm.getUsername()+"','"+registerForm.getPassword()+"')";
			
			PreparedStatement prm=con.prepareStatement(sql);
			i=prm.executeUpdate();
			
			
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(i==1){
			 String username=registerForm.getUsername();
			 HttpSession session = request.getSession(); 
			 session.setAttribute("username", username); 
		 return mapping.findForward("success");	
		}
		else{
			return mapping.findForward("fail");
		}
	}
}